[package]
name = "nats-provider"
version = "0.2.0"
authors = ["Kevin Hoffman <alothien@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wascc-codec = "0.5.0"
log = "0.4.8"
env_logger = "0.7.1"
crossbeam-channel = "0.4.2"
crossbeam = "0.7.3"
crossbeam-utils = "^0.7.0"
natsclient = "0.0.7"

